// ---------- geometry ----------
function makeMesh(g){const m={count:g.i.length};m.pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m.pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.p),gl.STATIC_DRAW);m.nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m.nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.n),gl.STATIC_DRAW);m.ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(g.i),gl.STATIC_DRAW);return m}
function boxGeo(w=1,h=1,d=1){const p=[],n=[],i=[];const faces=[[[0,0,1],[-w/2,-h/2,d/2],[w/2,-h/2,d/2],[w/2,h/2,d/2],[-w/2,h/2,d/2]],[[0,0,-1],[w/2,-h/2,-d/2],[-w/2,-h/2,-d/2],[-w/2,h/2,-d/2],[w/2,h/2,-d/2]],[[1,0,0],[w/2,-h/2,d/2],[w/2,-h/2,-d/2],[w/2,h/2,-d/2],[w/2,h/2,d/2]],[[-1,0,0],[-w/2,-h/2,-d/2],[-w/2,-h/2,d/2],[-w/2,h/2,d/2],[-w/2,h/2,-d/2]],[[0,1,0],[-w/2,h/2,d/2],[w/2,h/2,d/2],[w/2,h/2,-d/2],[-w/2,h/2,-d/2]],[[0,-1,0],[-w/2,-h/2,-d/2],[w/2,-h/2,-d/2],[w/2,-h/2,d/2],[-w/2,-h/2,d/2]]];for(const f of faces){const b=p.length/3;for(let k=1;k<5;k++){p.push(...f[k]);n.push(...f[0])}i.push(b,b+1,b+2,b,b+2,b+3)}return{p,n,i}}
function sphereGeo(r=1,seg=20,ring=14){const p=[],n=[],i=[];for(let y=0;y<=ring;y++){const v=y/ring,ph=v*Math.PI;for(let x=0;x<=seg;x++){const u=x/seg,th=u*Math.PI*2,s=Math.sin(ph),nx=Math.cos(th)*s,ny=Math.cos(ph),nz=Math.sin(th)*s;p.push(nx*r,ny*r,nz*r);n.push(nx,ny,nz)}}for(let y=0;y<ring;y++)for(let x=0;x<seg;x++){const a=y*(seg+1)+x,b=a+seg+1;i.push(a,b,a+1,b,b+1,a+1)}return{p,n,i}}
function cylinderGeo(rt=.5,rb=.5,h=1,seg=20){const p=[],n=[],i=[];for(let y=0;y<=1;y++){const rr=y?rt:rb,yy=(y-.5)*h;for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2,c=Math.cos(a),z=Math.sin(a),sl=(rb-rt)/h;n.push(c,sl,z);p.push(c*rr,yy,z*rr)}}for(let s=0;s<seg;s++){const a=s,b=s+seg+1;i.push(a,b,a+1,b,b+1,a+1)}const cap=(yy,rr,up)=>{const center=p.length/3;p.push(0,yy,0);n.push(0,up,0);const st=p.length/3;for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2;p.push(Math.cos(a)*rr,yy,Math.sin(a)*rr);n.push(0,up,0)}for(let s=0;s<seg;s++)up>0?i.push(center,st+s,st+s+1):i.push(center,st+s+1,st+s)};if(rt>0)cap(h/2,rt,1);if(rb>0)cap(-h/2,rb,-1);return{p,n,i}}
function torusGeo(R=1,r=.065,seg=44,tube=9){const p=[],n=[],i=[];for(let u=0;u<=seg;u++){const a=u/seg*Math.PI*2,ca=Math.cos(a),sa=Math.sin(a);for(let v=0;v<=tube;v++){const b=v/tube*Math.PI*2,cb=Math.cos(b),sb=Math.sin(b);p.push((R+r*cb)*ca,(R+r*cb)*sa,r*sb);n.push(cb*ca,cb*sa,sb)}}for(let u=0;u<seg;u++)for(let v=0;v<tube;v++){const a=u*(tube+1)+v,b=(u+1)*(tube+1)+v;i.push(a,b,a+1,b,b+1,a+1)}return{p,n,i}}
const meshes={box:makeMesh(boxGeo()),sphere:makeMesh(sphereGeo()),cylinder:makeMesh(cylinderGeo()),cone:makeMesh(cylinderGeo(0,.5,1,20)),torus:makeMesh(torusGeo())};
function draw(mesh,model,color,opacity=1,emissive=0,rim=.1,gloss=.25){gl.useProgram(meshProgram);gl.uniformMatrix4fv(ML.uModel,false,model);gl.uniformMatrix4fv(ML.uVP,false,VP);gl.uniform3fv(ML.uColor,color);gl.uniform3fv(ML.uCamera,CAMERA.eye);gl.uniform3f(ML.uLight,-.42,-.8,-.36);gl.uniform3f(ML.uFogColor,.042,.015,.066);gl.uniform1f(ML.uOpacity,opacity);gl.uniform1f(ML.uEmissive,emissive);gl.uniform1f(ML.uRim,rim);gl.uniform1f(ML.uGloss,gloss);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.pb);gl.enableVertexAttribArray(ML.aPos);gl.vertexAttribPointer(ML.aPos,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.nb);gl.enableVertexAttribArray(ML.aNormal);gl.vertexAttribPointer(ML.aNormal,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,mesh.ib);gl.drawElements(gl.TRIANGLES,mesh.count,gl.UNSIGNED_SHORT,0)}
function child(parent,local){const o=M4();mul(o,parent,local);return o}
function beamModel(a,b,r){const d=sub(b,a),L=len(d),y=norm(d),helper=Math.abs(y[1])>.95?[1,0,0]:[0,1,0],x=norm(cross(helper,y)),z=norm(cross(y,x)),mid=scale(add(a,b),.5);return basisMatrix(x,y,z,mid,[r,L,r])}
function orientedModel(pos,tangent,s=[1,1,1],roll=0){const y=norm(tangent),helper=Math.abs(y[1])>.92?[1,0,0]:[0,1,0],x=norm(cross(helper,y)),z=norm(cross(y,x));let m=basisMatrix(x,y,z,pos,s);if(roll){const q=M4();mul(q,m,RY(roll));m=q}return m}
function ringModel(pos,r,thick=1,roll=0){const normal=scale(camForward,-1),right=camRight,up=camUp;let m=basisMatrix(right,up,normal,pos,[r,r,thick]);if(roll){const q=M4();mul(q,m,RZ(roll));m=q}return m}
